### ISSUE TITLE
Code Style should follow Effective C++ guidelines

### ISSUE THREAD

**Issue by BenBE** [sengelha/streaming-percentiles-cpp#30]
To make the source more workable it should follow the guidelines suggested in [Effective C++](https://lost-contact.mit.edu/afs/rhic.bnl.gov/i386_sl305/app/codewizard-4.3/manuals/items_ec.htm).

Currently when using GCC with -Weffc++ there are several minor issues reported, which can be grouped into the following changes needed:

- Always list all declared members in the constructor's initializer list (this applies to field `m_S` missing, adding `m_S{}` fixes this)

- Make the ckms_* classes non-copyable by deleting their copy constructor and assignment operator.
  Adding something like
  ```cpp
  ckms_foo(const ckms_foo&) = delete;
  ckms_foo& operator=(const ckms_foo&) = delete;
  ```
  in the header for all ckms_* classes fixes this. At the moment, when ever you accidentally copy your object you create a double-free bug, as the constructor of each instance free's your impl object.

- Another note relates to the use of `using namespace std;`, which is [kinda bad practice](https://stackoverflow.com/q/1452721). It's so rarely actually useful in your code that the five or so cases where it is shortening the namespace reference (when accessing `std::min`, `std::max` and `std::numerical_limits`) it's actually shorter to skip `using namespace std;` and instead just qualify the places where these functions are used. I also despise people writing code where I have to guess the namespace their symbols come from ... ;-)

**Comment by sengelha** [comment]
Fixed in commit a4c0aa838e01e5fd262a8396956fe90be2d10392
